# This is a basic workflow to help you get started with Actions

name: app-prod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  debug-apk:
    name: Assemble App Debug apk
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: assemble release apk
        run: bash ./gradlew assembleGoogleplay --stacktrace
      
        
      - name: Sign android release
        uses: r0adkll/upload-google-play@v1
        with:
            serviceAccountJson: ${{ SERVICE_ACCOUNT_JSON }}
            packageName: com.example.MyApp
            releaseFile: ${{ SIGNED_RELEASE_FILE}}
            track: beta
            userFraction: 0.33
            whatsNewDirectory: /distribution/whatsnew
            mappingFile: /app/build/outputs/mapping/release/mapping.txt
